# Generated by Django 4.2.5 on 2024-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=255)),
                ('league_type', models.CharField(max_length=50)),
                ('league_logo', models.URLField(max_length=500)),
                ('country_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=10)),
                ('country_flag', models.URLField(max_length=500)),
            ],
        ),
    ]
