# Generated by Django 5.1.1 on 2024-10-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='injury',
            name='player',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
