# Generated by Django 4.2.5 on 2024-10-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('team_code', models.CharField(blank=True, max_length=10, null=True)),
                ('team_country', models.CharField(max_length=255)),
                ('team_founded', models.IntegerField(blank=True, null=True)),
                ('team_logo_url', models.URLField(blank=True, null=True)),
                ('team_venue_id', models.IntegerField(blank=True, null=True)),
                ('team_venue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_venue_address', models.CharField(blank=True, max_length=255, null=True)),
                ('team_venue_city', models.CharField(blank=True, max_length=255, null=True)),
                ('team_venue_capacity', models.IntegerField(blank=True, null=True)),
                ('team_venue_surface', models.CharField(blank=True, max_length=50, null=True)),
                ('team_venue_image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_date', models.DateTimeField()),
                ('timezone', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('league_name', models.CharField(max_length=255)),
                ('league_country', models.CharField(max_length=255)),
                ('league_logo_url', models.URLField()),
                ('league_flag_url', models.URLField()),
                ('league_season', models.CharField(max_length=255)),
                ('league_round', models.CharField(max_length=255)),
                ('match_home_team', models.CharField(max_length=255)),
                ('match_home_id', models.IntegerField()),
                ('match_away_team', models.CharField(max_length=255)),
                ('match_away_id', models.IntegerField()),
                ('match_home_team_logo_url', models.URLField()),
                ('match_away_team_logo_url', models.URLField()),
                ('match_home_winner', models.BooleanField(default=False)),
                ('match_away_winner', models.BooleanField(default=False)),
                ('match_referee', models.CharField(blank=True, max_length=255, null=True)),
                ('match_venue_id', models.IntegerField()),
                ('match_venue_name', models.CharField(max_length=255)),
                ('match_venue_city', models.CharField(max_length=255)),
                ('match_status_long', models.CharField(max_length=50)),
                ('match_status_short', models.CharField(max_length=10)),
                ('score_halftime_home', models.IntegerField(blank=True, null=True)),
                ('score_fulltime_home', models.IntegerField(blank=True, null=True)),
                ('score_extratime_home', models.IntegerField(blank=True, null=True)),
                ('score_penalty_home', models.IntegerField(blank=True, null=True)),
                ('score_halftime_away', models.IntegerField(blank=True, null=True)),
                ('score_fulltime_away', models.IntegerField(blank=True, null=True)),
                ('score_extratime_away', models.IntegerField(blank=True, null=True)),
                ('score_penalty_away', models.IntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_injurykick.league')),
            ],
        ),
    ]
