# Generated by Django 5.1.1 on 2024-10-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0002_injury_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='league',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
