# Generated by Django 5.1.1 on 2024-10-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0002_alter_league_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='country_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
