# Generated by Django 5.1.1 on 2024-10-16 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0002_remove_newsdata_categories_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastestsidelined',
            name='api_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_injurykick.player', to_field='api_id'),
        ),
    ]
