# Generated by Django 5.1.1 on 2024-10-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0003_alter_injury_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='injury',
            name='since',
            field=models.DateField(blank=True, null=True),
        ),
    ]
