# Generated by Django 5.1.1 on 2024-10-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0003_alter_league_country_alter_league_country_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='slug',
        ),
    ]
