# Generated by Django 5.1.1 on 2024-10-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0003_lastestsidelined_api_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('current_season', models.BooleanField(default=False)),
                ('fixtures_events', models.BooleanField(default=False)),
                ('fixtures_lineups', models.BooleanField(default=False)),
                ('fixtures_statistics_fixtures', models.BooleanField(default=False)),
                ('fixtures_statistics_players', models.BooleanField(default=False)),
                ('standings', models.BooleanField(default=False)),
                ('players', models.BooleanField(default=False)),
                ('top_scorers', models.BooleanField(default=False)),
                ('top_assists', models.BooleanField(default=False)),
                ('top_cards', models.BooleanField(default=False)),
                ('injuries', models.BooleanField(default=False)),
                ('predictions', models.BooleanField(default=False)),
                ('odds', models.BooleanField(default=False)),
                ('api_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_injurykick.league', to_field='api_id')),
            ],
            options={
                'unique_together': {('api_id', 'season_year')},
            },
        ),
    ]
