# Generated by Django 5.1.1 on 2024-10-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0004_leagueseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
                ('player', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('direction', models.CharField(max_length=10)),
                ('from_team', models.CharField(blank=True, max_length=100)),
                ('transfer_type', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Injury',
        ),
        migrations.RemoveField(
            model_name='teammapping',
            name='team_transfermarkt',
        ),
        migrations.RemoveField(
            model_name='playermapping',
            name='player_api',
        ),
        migrations.RemoveField(
            model_name='playermapping',
            name='player_transfermarkt',
        ),
        migrations.RemoveField(
            model_name='teammapping',
            name='team_api',
        ),
        migrations.DeleteModel(
            name='LeagueTeamLinkTransfermarktData',
        ),
        migrations.DeleteModel(
            name='PlayerMapping',
        ),
        migrations.DeleteModel(
            name='PlayerTransfermarktData',
        ),
        migrations.DeleteModel(
            name='TeamMapping',
        ),
    ]
