# Generated by Django 5.1.1 on 2024-10-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0004_alter_playerseasonstatistics_appearances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
