# Generated by Django 5.1.1 on 2024-10-14 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0004_alter_injury_since'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='categories',
        ),
    ]
