# Generated by Django 5.1.1 on 2024-10-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0005_remove_news_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(choices=[(0, 'General'), (3, 'Transfers'), (4, 'General'), (5, 'Match Previews'), (6, 'Featured'), (7, 'Internationals')], primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='categories',
            field=models.ManyToManyField(blank=True, default=None, to='app_injurykick.category'),
        ),
    ]
