# Generated by Django 5.1.1 on 2024-10-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0005_remove_news_slug_news_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='image_custom',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='image_custom',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='image_custom',
            field=models.URLField(blank=True, null=True),
        ),
    ]
