# Generated by Django 5.1.1 on 2024-10-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0005_remove_match_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('logo', models.URLField()),
                ('points', models.IntegerField()),
                ('goals_diff', models.IntegerField()),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'unique_together': {('league_id', 'season', 'rank')},
            },
        ),
    ]
