# Generated by Django 5.1.1 on 2024-10-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0005_transfer_delete_injury_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-date'], 'verbose_name': 'Transfer', 'verbose_name_plural': 'Transfers'},
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_team_link',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transfer',
            name='from_team_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='direction',
            field=models.CharField(choices=[('In', 'In'), ('Out', 'Out')], max_length=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='from_team',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='transfer_type',
            field=models.CharField(max_length=50),
        ),
    ]
