# Generated by Django 5.1.1 on 2024-10-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0006_league_image_custom_leaguestanding_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='away_draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_goals_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_goals_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='away_win',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_goals_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_goals_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='home_win',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='goals_against',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='goals_for',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='played',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaguestanding',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
