# Generated by Django 5.1.1 on 2024-10-13 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0007_leaguestanding_away_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='description_custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
