# Generated by Django 5.1.1 on 2024-10-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0007_remove_team_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='venue_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
    ]
