# Generated by Django 5.1.1 on 2024-10-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0008_leaguestanding_description_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='description_deduction',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
