# Generated by Django 5.1.1 on 2024-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0008_team_venue_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseasonstatistics',
            name='api_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
