# Generated by Django 5.1.1 on 2024-10-18 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0008_alter_transfer_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseasonstatistics',
            name='status',
            field=models.CharField(default='Current', max_length=50),
        ),
    ]
