# Generated by Django 5.1.1 on 2024-10-19 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0009_playerseasonstatistics_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_team_name', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='app_injurykick.team', to_field='api_id')),
            ],
            options={
                'verbose_name': 'Team Mapping',
                'verbose_name_plural': 'Team Mappings',
            },
        ),
    ]
