# Generated by Django 5.1.1 on 2024-10-13 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0009_leaguestanding_description_deduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='slug',
        ),
    ]
