# Generated by Django 5.1.1 on 2024-10-07 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0009_alter_teamseasonstatistics_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='league',
            new_name='league_id',
        ),
    ]
