# Generated by Django 5.1.1 on 2024-10-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0010_teammapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='venue_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
