# Generated by Django 5.1.1 on 2024-10-07 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0010_rename_league_match_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='app_injurykick.league', to_field='api_id', unique=True),
        ),
    ]
