# Generated by Django 5.1.1 on 2024-10-21 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0011_alter_team_venue_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguestanding',
            name='update_time',
        ),
    ]
