# Generated by Django 5.1.1 on 2024-10-13 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0011_alter_playerseasonstatistics_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='legend_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
