# Generated by Django 5.1.1 on 2024-10-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0012_alter_match_league_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseasonstatistics',
            name='played_away',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teamseasonstatistics',
            name='played_home',
            field=models.IntegerField(default=0),
        ),
    ]
