# Generated by Django 5.1.1 on 2024-10-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0012_remove_leaguestanding_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguestanding',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
