# Generated by Django 5.1.1 on 2024-10-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0013_alter_leaguestanding_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
