# Generated by Django 5.1.1 on 2024-10-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0013_leaguestanding_legend_color_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country_flag_custom',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='name_custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='type_custom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
