# Generated by Django 5.1.1 on 2024-10-13 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0014_league_country_flag_custom_league_name_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country_custom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
