# Generated by Django 5.1.1 on 2024-10-09 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0014_remove_teamseasonstatistics_api_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamseasonstatistics',
            old_name='league',
            new_name='league_name',
        ),
        migrations.RenameField(
            model_name='teamseasonstatistics',
            old_name='team',
            new_name='team_name',
        ),
    ]
