# Generated by Django 5.1.1 on 2024-10-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0015_fixtureevents_fixturelineupplayer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureteamstatistics',
            name='value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
