# Generated by Django 5.1.1 on 2024-10-09 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0015_rename_league_teamseasonstatistics_league_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamseasonstatistics',
            old_name='league_name',
            new_name='league_id',
        ),
        migrations.RenameField(
            model_name='teamseasonstatistics',
            old_name='team_name',
            new_name='team_id',
        ),
    ]
