# Generated by Django 5.1.1 on 2024-10-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0015_league_country_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='country_code_custom',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
