# Generated by Django 5.1.1 on 2024-10-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0016_rename_league_name_teamseasonstatistics_league_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamseasonstatistics',
            old_name='league_id',
            new_name='league_name',
        ),
        migrations.RenameField(
            model_name='teamseasonstatistics',
            old_name='team_id',
            new_name='team_name',
        ),
    ]
