# Generated by Django 5.1.1 on 2024-10-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0017_alter_fixturelineupplayer_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureplayerstatistics',
            name='offsides',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
