# Generated by Django 5.1.1 on 2024-10-13 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0017_leagueteamlinktransfermarktdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueteamlinktransfermarktdata',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
