# Generated by Django 5.1.1 on 2024-11-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0019_alter_fixtureplayerstatistics_substitute'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='form',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaguestanding',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
