# Generated by Django 5.1.1 on 2024-11-01 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0020_leaguestanding_form_leaguestanding_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguestanding',
            name='status',
        ),
    ]
