# Generated by Django 5.1.1 on 2024-10-13 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0020_leagueteamlinktransfermarktdata_trfmt_league_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagueteamlinktransfermarktdata',
            name='trfmt_league_id',
        ),
    ]
