# Generated by Django 5.1.1 on 2024-11-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0022_alter_leaguestanding_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
