# Generated by Django 5.1.1 on 2024-11-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0023_match_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguestanding',
            name='league_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_injurykick.league', to_field='api_id'),
        ),
    ]
