# Generated by Django 5.1.1 on 2024-11-03 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_injurykick', '0024_alter_leaguestanding_league_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidelined',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_sidelined', to='app_injurykick.player', to_field='api_id'),
        ),
    ]
